# Generated by Django 5.0.3 on 2024-05-29 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0017_remove_userrole_creating_comment_alter_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustask',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='status_task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 29)),
        ),
    ]
