# Generated by Django 5.0.3 on 2024-05-31 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0019_remove_statustask_image_alter_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statustask',
            name='id_board',
        ),
    ]
