# Generated by Django 5.0.3 on 2024-05-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0020_remove_statustask_id_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='postition',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
