# Generated by Django 5.0.3 on 2024-05-31 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0021_task_postition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='postition',
            new_name='position',
        ),
    ]
