# Generated by Django 5.0.3 on 2024-06-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0023_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
